language: python
python:
  - "2.7"

before_install:
  - pip install coverage
  - pip install python-coveralls
  - pip install codecov

install: "pip install -r requirements.txt"

script: coverage run --source=extrapolation regression_tests.py

after_success:
  - coveralls
  - codecov
